<a href="https://colab.research.google.com/github/Lokesh8Goenka/MDSC-101/blob/main/23906_MDSC101-EigenValues.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2/9/23

In [63]:
import numpy as np
from numpy import linalg as LA

In [22]:
# user input for dimension of the matrix.
col = int(input("Column of the matrix."))
row = int(input("Row of the matrix."))

mat = []
for i in range(row):
  l1 = []
  mat.append(l1)
  for j in range(col):
    # user input element
    ele = int(input())
    l1.append(ele)

print(mat)

Column of the matrix.2
Row of the matrix.3
1
2
3
4
5
6
[[1, 2], [3, 4], [5, 6]]


## A (A^T)

In [23]:
mat_T = np.transpose(mat)
mat_T

array([[1, 3, 5],
       [2, 4, 6]])

In [29]:
mat_mul = np.matmul(mat,mat_T)
mat_mul

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [44]:
eigenval1, eigenvector1 = LA.eig(mat_mul)

print("Eigen Value:", eigenval1)
print("Eigen Vector:\n", eigenvector1)

Eigen Value: [ 0.26450509 90.73549491]
Eigen Vector:
 [[-0.78489445 -0.61962948]
 [ 0.61962948 -0.78489445]]


## A^T (A)

In [35]:
mat_mul = np.matmul(mat_T,mat)
mat_mul

array([[35, 44],
       [44, 56]])

In [40]:
eigenval2, eigenvector2 = LA.eig(mat_mul)

print("Eigen Value:", eigenval2)
print("Eigen Vector:\n", eigenvector2)

Eigen Value: [ 0.26450509 90.73549491]
Eigen Vector:
 [[-0.78489445 -0.61962948]
 [ 0.61962948 -0.78489445]]


In [69]:
Lamb1 = np.diag(np.sqrt(eigenval1))
Lamb2 = np.diag(np.sqrt(eigenval2))

print(Lamb1)
print(Lamb2)

[[0.51430058 0.        ]
 [0.         9.52551809]]
[[0.51430058 0.        ]
 [0.         9.52551809]]
